default_method_hyperparameters:
  # ===== Generation configs ======
  attack_gen_config:
    max_new_tokens: 2048
    temperature: 1.0
    stop_tokens: ['|']

openrouter_api_key: &key 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

qwen-2.5-72b:
  attack_model:
    model_name_or_path: openrouter/deepseek/deepseek-chat-v3-0324
    token: *key
    fschat_template: chatgpt
  top_k_persuasion_taxonomy: 5

top_5:
  attack_model:
    model_name_or_path: mistralai/Mixtral-8x7B-Instruct-v0.1
    use_vllm: True
    num_gpus: 2
    dtype: bfloat16
  top_k_persuasion_taxonomy: 5

full_40:
  attack_model:
    model_name_or_path: mistralai/Mixtral-8x7B-Instruct-v0.1
    use_vllm: True
    num_gpus: 2
    dtype: bfloat16
  top_k_persuasion_taxonomy: 40